### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Spechtus** [alpha-xone/xbbg#1]
Since the new update is being released I have this Error message when I try to use the xbbg-module.
![index](https://user-images.githubusercontent.com/47421482/52415903-9e696f80-2ae8-11e9-8683-3a409d4c1f58.jpeg)

**Comment by alpha-xone** [comment]
Looks like `pdblp` is not properly installed. Could you try reinstalling it?

**Comment by alpha-xone** [comment]
Will close this in 2 days if no more comments
