### ISSUE TITLE
Null service handle error

### ISSUE THREAD

**Issue by e-ercan** [alpha-xone/xbbg#10]
Hi, thanks for the package. 

I'm sure it's my fault but I've tried everything I can think of but I'm unable to get it working. 

I couldn't find anyone with the same issue or anything related to blpapi that helped

I've installed according to instruction, matched the versions of the C++ SDK (3.14.1xx) to the python version 3.14 and moved the blpapi ddls to the correct place

When I try to run the examples I think xbbg.blp isnt able to establish a connection properly

![67BCF766-BED3-45B3-8E5C-1898052E9EAA](https://user-images.githubusercontent.com/10644527/72417979-10086e00-37ce-11ea-9123-4a3e81344801.jpeg)

I tried manually using blpapi to establish a connection which appears to work (despite the error returned, session.start() returns true) 

![77FC4667-AC9B-458D-9CD3-89AE1E66B1C5](https://user-images.githubusercontent.com/10644527/72418314-b05e9280-37ce-11ea-84e8-8e7deaa5067c.png)

I tried looking through conn.py but wasn't able to resolve it myself 

Interestingly the live function appears to work

![9275B359-6D95-4564-A434-BBB0D282A17D](https://user-images.githubusercontent.com/10644527/72418396-dd12aa00-37ce-11ea-828f-3998152d7c4e.png)

Not sure what to try next, I've tried reinstalling from scratch but no luck

Thank you for any help, much appreciated

**Comment by alpha-xone** [comment]
Which version are you using? I just tried below two (date of `bdib` is 2019 cause we can only get intraday data within half an year) and both work (you can add `log='debug'` to see what exactly have been sent to Bloomberg section):

![image](https://user-images.githubusercontent.com/41174521/72435246-94f88500-37d8-11ea-8705-ef695fb78c6a.png)

In your manual connection code, can you try below to see what happens:

    req = ref.createRequest('ReferenceDataRequest')

Looks like something is wrong `ReferenceDataRequest`.

**Comment by e-ercan** [comment]
Thanks for the quick reply

I'm using the latest version of xbbg installed via pip, same with blpapi, and the 3.14 major version of the Python and C++ SDK downloaded from WAPI on Bloomberg

This is the ReferenceDataRequest and the output which seems to have worked

![1](https://user-images.githubusercontent.com/10644527/72488094-11847580-3864-11ea-88e4-2eeb47b8d6e4.png)

The result it returns for PX_LAST is 7 so I think I'm managing to connect to the API and haven't messed up the install of blpapi (I think)

The next image is the error I get on the **first** attempt to execute the call

![2](https://user-images.githubusercontent.com/10644527/72488096-11847580-3864-11ea-827a-bfc2d46d33d9.png)

This image is the error I get every attempt afterwards

![3](https://user-images.githubusercontent.com/10644527/72488098-11847580-3864-11ea-99ec-2c4c60296726.png)

Thought that might be useful

Thanks

**Comment by alpha-xone** [comment]
Found the problem - there are some API changes of `blpapi` from 3.13.1 to 3.14.0. I was using 3.13.1 before.

You can download the C++ experimental API from Bloomberg website (currently still 3.13.x) and install 3.13.1 as temporary solution:

    pip install blpapi==3.13.1 --index-url=https://bloomberg.bintray.com/pip/simple

Will update the package later - guess will take some time.

**Comment by e-ercan** [comment]
Thank you, I really appreciate it

**Comment by alpha-xone** [comment]
Easier than I thought. Now it should be ok.

Kindly update and check if it works. Thx

**Comment by e-ercan** [comment]
Working perfectly now, cheers :)
