### ISSUE TITLE
regression BDP

### ISSUE THREAD

**Issue by 3kwa** [alpha-xone/xbbg#11]
When upgrading from 0.5.0 to 0.6.0 noticed a regression in BDP when requesting the open price and the current bid for a product: the open price is identical to the bid even when they are not.

**Comment by alpha-xone** [comment]
do you have more details, i.e., ticker name, date, etc.?

**Comment by 3kwa** [comment]
Noticed this morning AEST with most if not all the JT Equity tickers in NK225. Will attempt to write a simple failing example.

**Comment by alpha-xone** [comment]
just tried couple of names - seems fine:

    In [1]: blp.bdp('FP FP Equity', ['Open', 'Last_Price'])
    Out[1]:
                  open  last_price
    FP FP Equity 45.17       44.84

**Comment by alpha-xone** [comment]
Will close soon if the problem cannot be replicated @3kwa
