### ISSUE TITLE
Close of the day

### ISSUE THREAD

**Issue by KEVORK890** [alpha-xone/xbbg#13]
Hi, is there a way to obtain the correct close value of the day? 
Indeed, the "last price" value does not really match with the close.
Thanks

**Comment by alpha-xone** [comment]
This sounds like not a package related issue.
Please always give examples to show what you really mean.

**Comment by KEVORK890** [comment]
I have been using the function blp.bdh to retrieve the historical  "Open", "High", "Low" and "Last Price" data. Although the values of the first three fields are correct, the last price doesn't really match with the historical close price of the day

**Comment by alpha-xone** [comment]
Please show explicit example including screenshots, otherwise will close this issue.

**Comment by KEVORK890** [comment]
Example showed in the image below:  ticker "ED1 Comdty"
The close price on the 3rd March from Bloomberg terminal is different than the "last price" from "blh" function (99.0100 vs 98.9775). On the other hands, "open" values on 4th March match (99.0150)

![image](https://user-images.githubusercontent.com/22801538/75971424-0d72ec80-5ed2-11ea-87cb-3826871580f1.png)

**Comment by alpha-xone** [comment]
RHS is not closing price...
Closing price is based on exchange hours, not by end-of-day of your timezone.

**Comment by KEVORK890** [comment]
> RHS is not closing price...
> Closing price is based on exchange hours, not by end-of-day of your timezone.

In this case, 22:59 corresponds to the close time of the exchange.
In any case, how can I fetch the close value? thanks

**Comment by alpha-xone** [comment]
`bdh` dowloads EOD values from HCP<GO> page.
If you really need intraday data, use `bdib` and do data manipulation necessary.
But doubt that's what you really want.
