### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by spyamine** [alpha-xone/xbbg#16]
Hi,

How can we access the log functionality and put everything in a file. 

I know that i can use , log='debug' but how can i access the details and log it to a file?

thanks

**Comment by alpha-xone** [comment]
Can try passing below arguments but not sure if it works. If not can add it in next update:

> log_file='pre.log', types='file|stream'

**Comment by spyamine** [comment]
Hi, 

It's not working when i add this in the bdh function. it goes as overrides..

**Comment by alpha-xone** [comment]
ok cool. will make this available next update

**Comment by spyamine** [comment]
Many thanks,

I have also add modification to your code to get intraday data on a range of dates. and removed the necessity to have exchange information. all the data we get from bloomberg is UTC. so i think no need to add complexity for the time.
