### ISSUE TITLE
Exist the Excel BPGE function in xbbg?

### ISSUE THREAD

**Issue by paduel** [alpha-xone/xbbg#17]
Congratulations on what a great job this library is.

I use the **BPGE** function in Excel and I would like to take the same information using xbbg. But I couldn't find the way to do it. Is it possible?

`BPGE (Page Based Data) : Imports data from pages contributed to the Bloomberg by outside sources.`

Thanks in advance.

**Comment by alpha-xone** [comment]
I personally did not use this function before. If you're familiar with it feel free to add to the package.

**Comment by alpha-xone** [comment]
Will close this if there's no more comments this week.

**Comment by paduel** [comment]
The truth is that I'm not familiar with how the native api treats that excel function, or even if it can.

Later on when I have time I will investigate it, if I can integrate it into xbbg I will send a pull request.

I close the issue.
