### ISSUE TITLE
cannot get best_bid in bdp

### ISSUE THREAD

**Issue by l976308589** [alpha-xone/xbbg#18]
blp.bdp(tickers,flds=['bid','best_bid'])
I can get bid,but best_bid

**Comment by alpha-xone** [comment]
In Excel, seems it always return #N/A N/A first, then the actual value.
Need to loop server responses (and even delayed responses) recursively for this one.
Not sure got time to resolve this recently.
Could you help looking into this?

**Comment by l976308589** [comment]
I'm on call

**Comment by alpha-xone** [comment]
can only be retrieved from `blp.live`
