### ISSUE TITLE
Unable to get Tick data for Commodity Securities

### ISSUE THREAD

**Issue by eanderson-skylar** [alpha-xone/xbbg#19]
For example:

`from xbbg import blp
import pandas as pd
import numpy as np
import datetime

cur_dt = pd.Timestamp('today', tz='America/New_York')
recent = pd.bdate_range(end='today', periods=2, tz='America/New_York')
pre_dt = max(filter(lambda dd: dd < cur_dt, recent))
pre_dt.date()

blp.bdtick('NGQ20 Comdty', dt=pre_dt).tail()`

returns error: 'Unknown string format: 2020-08-03 None'

**Comment by alpha-xone** [comment]
because exchange info is missing for this name. you can add relevant info to .yml file (see README for instruction).

another solution is use `ref='ES1 Index'` as argument - but this is not yet available for `bdtick` (only works for `bdib` now).

**Comment by alpha-xone** [comment]
This is resolved in `0.7.1b3`
