### ISSUE TITLE
Do you plan to add subscriptions?

### ISSUE THREAD

**Issue by auenbauer** [alpha-xone/xbbg#2]

**Comment by alpha-xone** [comment]
no plan yet. any suggestions?

**Comment by auenbauer** [comment]
I would find it great if subscriptions could be added because it seems that non of the other blpapi wrappers have it but unfortunately given my limited Python coding knowledge I can not directly contribute anything to the project.

**Comment by alpha-xone** [comment]
By subscription you mean receiving live data right? I'm not familiar with this area and would expect python to be very unstable after pulling data after a while - memory blows up randomly in many cases. It would be a lot more easier (and more stabler) to use python to prepare data for Excel, then use Excel to receive live data.

Subscription works much better in other languages like C++ / C# / Java.

**Comment by auenbauer** [comment]
Yes I mean the streaming of live data for a list of securities by the subscription method. I can be wrong but in my mind subscriptions, in theory, should be a better method than a reference data call (query/ reference method) if you like to receive every data point for one or more securities right at the time when something like a transaction takes place.  With the reference method you need to "refresh" a query over and over again in short intervals and most of the time you don't get data because nothing has happened. Do you know what I mean?

**Comment by alpha-xone** [comment]
Yes got you. This is way out of the scope of this little project. As mentioned, Excel is a much better choice.

**Comment by alpha-xone** [comment]
subscription coming soon
