### ISSUE TITLE
BDS with custom portfolio returns nothing

### ISSUE THREAD

**Issue by walterkissling** [alpha-xone/xbbg#20]
Hello, I am able to pull portfolio information for a custom portfolio in Excel and in xbbg using BDP only. When I try to pull data using BDS nothing is returned.

The code I am using is:
`blp.bds('<PORT ID> Client','PORTFOLIO_DATA')`

And the results is just "__". If I use the same formula in Excel it works fine.

Anyone having the same issue?

**Comment by walterkissling** [comment]
In case anyone is interested, the fix is to create a new function, much like BDP, but replace:

`    request = service.createRequest('ReferenceDataRequest')`

with

`request = service.createRequest('PortfolioDataRequest')`

**Comment by alpha-xone** [comment]
Thanks for update. In this case we may need to create another `bd` function to connect to this portfolio request.

**Comment by alpha-xone** [comment]
added one parameter to solve this temporarily. could you check out if it works:
https://github.com/alpha-xone/xbbg/blob/e5c4e43d8697eca16389926e5ccf130a12c8b896/xbbg/blp.py#L56

Can install below beta to try out:
pip install xbbg==0.7.1b2

**Comment by walterkissling** [comment]
Thanks! Yes it works fine.

**Comment by alpha-xone** [comment]
Great

**Comment by geekfred** [comment]
Hello guys, I know this is an old thread but I really need some help. I am trying to retrieve all the data of a portfolio and I keep getting {} as response.

This is what I am running:

`def getPortfolio():

portfolio = request.args.get('portfolio')

result = blp.bds(tickers=["U302412345-20", flds=['PORTFOLIO_DATA'], use_port=True)
result_object = result.to_json[orient = 'columns']

return result_object
`

If anyone could give me a light. There's equities, cash, and some other things in that portfolio ID I am calling.

Thanks.

**Comment by mg3146** [comment]
What kind of portfolio is that / ticker is that ?

**Comment by geekfred** [comment]
That's the portfolio ID. What am I supposed to pass? Thanks.

**Comment by mg3146** [comment]
Oh I just didn’t even know this was possible, kinda neat

**Comment by geekfred** [comment]
Yes, it would be neater if I knew how to do it 😂😂😂

**Comment by mg3146** [comment]
Haha, I hear you.  I guess first question is, how do you do in the excel API? Same way you have it in the code ?

**Comment by geekfred** [comment]
Yep, doing exactly that. But I'm getting { } and that's it.

**Comment by mg3146** [comment]
Is there anything in Result before calling to json ?

**Comment by geekfred** [comment]
Nope, nadda..

**Comment by geekfred** [comment]
Anyone has any idea? @alpha-xone ?

**Comment by walterkissling1** [comment]
Don't know if you figured it out already but I think what's missing is you need to append the world "Client" at the end of the portfolio id. So in your example it would be "U302412345-20 Client".
