### ISSUE TITLE
Is BQR MSG1 supported?

### ISSUE THREAD

**Issue by OdinCosta** [alpha-xone/xbbg#22]
Hi,
Congrats and thanks for the amazing work put so far! I'm wondering if the actual library would support the BQR excel function?

I've looked into WAPI <GO> and it seems to suggest that you can build a proxy using the intraday tick data. 

Here is the snippet:

> How do I emulate the BQR() Bloomberg formula in Microsoft Excel via the API interfaces?

> To emulate the BQR formulas using the Desktop or Server API is a two step process. Under the hood of the formula in Microsoft Excel, these are the requests being made:
> 
> An Intraday Tick Request, which is using the //blp/refdata service and the "IntradayTickRequest" operation (i.e. request type).
> A subscription to BID, ASK, BEST_BID and BEST_ASK for that same instrument. This uses the //blp/mktdata service.
> 
> For example, if you have the Microsoft Excel formula:
> 
>     =BQR("IBM/ MSG1 Corp","-2D","","query=time,broker,bid,ask")
> 
> 
> Under the hood, we are calculating 2 days back and determining the absolution startdate/time and setting the enddate/time to now. We are then setting the EventTypes property (i.e. element) to BID and also to ASK. For the "Broker", we are setting the "includeBrokerCodes" property to "true". Along with the security ("IBM/ MSG1 Corp"), this makes up our intraday tick request.
> 
> Once you get this data back, you will then subscribe to this security, along with BEST_BID, BEST_ASK, BID and ASK. Unfortunately, we do not provide an example of this, so it will be up to you to develop this. You can obtain most of the information you need from the IntradayTickExample and the SimpleSubscriptionExample examples in the Desktop API or the Server API SDK.

I was wondering if I could try it on with your blp.bdib using the /MSG1 source, but not sure if I need to modify anything on the root files. Any idea?

Thank you!

**Comment by alpha-xone** [comment]
Not much experience in the fixed income area. See if anyone could contribute to this direction.

**Comment by m3ridian-zero** [comment]
Hi @OdinCosta! 🎉

Great news - BQR support has been implemented and is available in PR #192!

## New `bqr()` function

The implementation follows the approach you outlined from WAPI - using `IntradayTickRequest` with `includeBrokerCodes=true` to emulate Excel's `=BQR()` formula.

### Usage

```python
from xbbg import blp

# With date offset (like Excel BQR)
df = blp.bqr("IBM US Equity@MSG1", date_offset="-2d")

# With ISIN
df = blp.bqr("/isin/US123456789@MSG1", date_offset="-2d")

# With explicit date range
df = blp.bqr("XYZ 4.5 01/15/30@MSG1 Corp", start_date="2024-01-15", end_date="2024-01-17")

# Trade events only
df = blp.bqr("XYZ 4.5 01/15/30@MSG1 Corp", date_offset="-1d", event_types=["TRADE"])
```

### Output columns

- `ticker` - Security identifier
- `time` - Quote timestamp
- `event_type` - BID, ASK, or TRADE
- `price` - Quote price
- `size` - Quote size
- `broker_buy` - Broker code for bid
- `broker_sell` - Broker code for ask

### Features

- Full multi-backend support (pandas, polars, pyarrow, duckdb)
- Date offset format (`-2d`, `-1w`, `-3h`) matching Excel BQR
- Works with Bloomberg tickers and ISINs with `@MSG1` pricing source

Once the PR is merged, this will be available in the next release. Thanks for the feature request!

**Comment by thestockman27** [comment]
Does this happen to support the "AskSpread" and "BidSpread" fields?

**Comment by m3ridian-zero** [comment]
Hi @thestockman27 — yes! As of the latest push to `main`, `bqr()` now supports `include_spread_price=True` which returns the `spreadPrice` field for each tick. This uses Bloomberg's `includeSpreadPrice` element on the `IntradayTickRequest`.

### Usage

```python
from xbbg import blp

df = blp.bqr(
    "US037833FB15@MSG1 Corp",
    date_offset="-2d",
    include_broker_codes=True,
    include_spread_price=True,
)
```

This returns columns: `ticker`, `time`, `type`, `value`, `size`, `spreadPrice`, `brokerBuyCode`, `brokerSellCode`.

Note that spread data availability depends on the security and pricing source — you'll typically need the `@MSG1` suffix to get dealer-level data including spreads.

There's also `include_yield=True` if you need yield data alongside price.

**Comment by thestockman27** [comment]
Hey thanks for the quick reply and your attention on this, not to mention all of your dev work!

I'm afraid that I didn't have luck with that suggestion. Wondering if we aren't on the same page. 

I am looking for the bid and ask quoted as a spread over treasuries. This is an option in the BQR excel templates that Bloomberg makes available on the terminal.

So I'd be looking for a broker quoting a corporate bond at 68 bid / 65 ask, rather than the price. Theoretically you could back into the spread using a function similar to bloombergs YAS function, but you'd have to retrieve other fields first

Hopefully that clears up my request, again huge thanks to you.
