### ISSUE TITLE
Using bdp to get last price (px_last) of list of tickers in common currency, i.e. which override to use?

### ISSUE THREAD

**Issue by GreekQuant** [alpha-xone/xbbg#24]
Which override arguments should I use with bdp in order to get all last prices in USD say, even though the list of tickers has companies from all over the world?

**Comment by alpha-xone** [comment]
Cannot.

Please don't open issues unrelated to this package.
No 1 place to ask is the bbg helpdesk and 2nd is StackOverflow.
