### ISSUE TITLE
support for different authentication method

### ISSUE THREAD

**Issue by anxl2008** [alpha-xone/xbbg#26]
In core/conn.py, can the connect_bbg() method be modified to allow different connection method? I am connecting with bloomberg server api and I will need to manually modify the function to make it work. I think this can simply be done by allowing user to declare and pass a blpapi.session.Session object into the function.

**Comment by alpha-xone** [comment]
can try installing this version to try out: [v0.7.6a1](https://github.com/alpha-xone/xbbg/releases/tag/v0.7.6a1)

**Comment by anxl2008** [comment]
> can try installing this version to try out: [v0.7.6a1](https://github.com/alpha-xone/xbbg/releases/tag/v0.7.6a1)

This works, thanks. 

Does it make sense to have a stand alone login interface for alternative connection method? Passing a session object to bdp() call after first login attempt/wrapping it in if statement doesn't seem an elegant solution.

**Comment by alpha-xone** [comment]
Not sure how server API works. In normal circumstances login is handled by Bloomberg.
