### ISSUE TITLE
bds produce duplicated results

### ISSUE THREAD

**Issue by anxl2008** [alpha-xone/xbbg#29]
Sample call: 
'blp.bds(['AAPL US Equity', 'IBM US Equity', 'T US Equity', 'F US Equity'], flds = ['EQY_DVD_ADJUST_FACT'])'

This will produce duplicated output for same ticker. This bug can be fixed by altering blp.bds() and blp.\_bds\_(). 

In bds(): 
request was created and passed to map(part, tickers). The map function will keep appending to request until all tickers are iterated.

As a consequence, in \_bds\_():
- map for AAPL: request = ['AAPL']
- map for IBM: request = ['AAPL', 'IBM']
- map for T: request = ['AAPL', 'IBM', 'T'}
...

This can be fixed by moving process.create_request() call from bds() to inside the \_bds\_() function.

**Comment by alpha-xone** [comment]
Great advice. Should be good in 0.7.6a3.
