### ISSUE TITLE
BDS not downloading sometimes

### ISSUE THREAD

**Issue by IgnacioAnguita** [alpha-xone/xbbg#41]
Hi,

When I run the following command: 

`blp.bds(ISIN + " Corp", "ASW_CASHFLOWS")  `

In most cases it works properly (a bit slow), however in some specific cases (some custom bonds) I get empty dataframes:

Empty DataFrame
Columns: []
Index: []

These custom bonds work properly on excel.

I have tried with multiple fields as well as bds/bdp and although they work on excel they do not  when using the library. Also I have tested multiple custom bonds and they all work perfectly fine. Is it possible that it needs some specific fields to be informed?

**Comment by alpha-xone** [comment]
Should be a connection issue - use `timeout` to wait for a bit longer: for example `bds(..., timeout=5000)` to wait for 5 seconds.
