### ISSUE TITLE
xbbg requesting intraday interval

### ISSUE THREAD

**Issue by fredysarmiento12** [alpha-xone/xbbg#44]
Hi,

I have 2 questions:
1. Does anyone know if it is possible to request time intervals on intraday data in xbbg?

The following code gives me the whole day 1-minute intervals and I want to request, for instance, only from 7 am to 10 am.

`df= blp.bdib(ticker='EURUSD Curncy', dt='2021-07-28',ref = 'CurrencyGeneric')`

2.  I am in London, but the data I get, has the time from NY,  how can I get data with London hours?

thanks

**Comment by alpha-xone** [comment]
1. Can try `df.between_time('7:00', '10:00')`.
2. Timezone of security depends on exchange rather than where you are. Use `df.tz_convert('UTC')` to convert into your timezone.

**Comment by fredysarmiento12** [comment]
Great ! Many thanks.

df.between_time, worked perfectly.

Still, the time zone is showing the data in New York time, wondering if I need to actually do anything to tell the system my local time London?

**Comment by fredysarmiento12** [comment]
Actually, it is working with:

df.tz_convert('Europe/London')

Many thanks for your help.
