### ISSUE TITLE
BUG: Unable to pull index members field

### ISSUE THREAD

**Issue by rgkimball** [alpha-xone/xbbg#45]
Hello!

I am trying to pull a list of index members but some of the Dataframe standardization operations in the [bdp](https://github.com/alpha-xone/xbbg/blob/5a92549f1dbdbf70a93c03b35a7f6d08206c8c2d/xbbg/blp.py#L63) function do not function correctly when there are duplicate entries in the index:

```
blp.bdp('RAY Index', 'INDX_MEMBERS')
```
Result  (when trying to unstack): *ValueError: Index contains duplicate entries, cannot reshape*

`res.head()` at error:

```
      ticker         field Member Ticker and Exchange Code
0  RAY Index  INDX_MEMBERS                            A UN
1  RAY Index  INDX_MEMBERS                           AA UN
2  RAY Index  INDX_MEMBERS                          AAL UW
3  RAY Index  INDX_MEMBERS                          AAN UN
4  RAY Index  INDX_MEMBERS                         AAON UW
```

**Comment by alpha-xone** [comment]
need to use `blp.bds` for this

**Comment by rgkimball** [comment]
My mistake, thanks!

**Comment by rgkimball** [comment]
@alpha-xone This is a bit strange - is the request somehow capped at 2,500 securities? RAY should be returning 2,997.

```python
members = blp.bds('RAY Index', 'INDX_MEMBERS')
members.shape  # (2500, 1)
```

**Comment by alpha-xone** [comment]
it's possible - can confirm with helpdesk

**Comment by David-Woroniuk** [comment]
@rgkimball - please note that all "INDX_MEMBERS" requests are capped at 2500 securities. For larger indices, you can use "INDX_MEMBERS2" and "INDX_MEMBERS3" to retrieve 2500-5000 and 5000-7500 respectively.

**Comment by rgkimball** [comment]
@David-Woroniuk Wasn't aware but that's a great tip, thank you!
