### ISSUE TITLE
blp.bds is doing a weird rounding

### ISSUE THREAD

**Issue by laygr** [alpha-xone/xbbg#5]
If you try this:
`blp.bds('ADP CHNG Index', "ECO_RELEASE_DT_LIST")`

You will get some weird values that don't match what is showed in bloomberg's terminal.

The library pdblp seems to get right; the output of the next code matches bloomberg's terminal:
`con.bulkref('ADP CHNG Index', 'ECO_RELEASE_DT_LIST')`

The output should be a list of dates. The output of xbbg will contain '20180132', while the correct value is '20180131' as showed in bloomberg's terminal and by the pdblp library.

I was using xbbg v0.1.24; when I encountered this error I upgraded to v0.3.0 but the error persists.

**Comment by alpha-xone** [comment]
This issue comes `pandas`.

A quick fix would be removing `downcast` kwarg at line 229 in file [assist.py](https://github.com/alpha-xone/xbbg/blob/master/xbbg/core/assist.py):

`.apply(pd.to_numeric, errors='ignore')`
