### ISSUE TITLE
blp.bdib doesn't work for commodity futures

### ISSUE THREAD

**Issue by josephchenhk** [alpha-xone/xbbg#52]
Tried to put "GC"/"GC1"/"GCZ" to assets.yml in Comdty, and used the following code to retrieve intraday bar data:

> blp.bdib('GCZ1 Comdty', dt='2021-02-19', typ='TRADE')

But just returned empty data. Any advice?

**Comment by alpha-xone** [comment]
You can put "GC" into assets.yml and use GC1 Comdty / GC2 Comdty to get first / second month of futures data.
For now, using futures contract (GC) + exact month (Z1) is not supported yet.
