### ISSUE TITLE
blp.bds is not working

### ISSUE THREAD

**Issue by TheGr8Destructo** [alpha-xone/xbbg#6]
Hi - thanks for the package - I am having an issue in that bds is not working at all I get the following when i try to run a BDS query. I run a bulk ref query in pdblp and I get results?

blp.bds('XS1577949149 corp','TOP_20_HOLDERS_PUBLIC_FILINGS')
**AttributeError: module 'xbbg' has no attribute 'bds'**

I installed with pip.

Please can you let me know if the bds call has been deprecated or has been amended and what i should do to fix the issue. 

Thanks

**Comment by alpha-xone** [comment]
it's working for me.
did you install the package according to instruction?
